// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster_status.proto

package com.cleo.clarify.server.clusterstatus;

public final class ClusterStatusProto {
  private ClusterStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clusterstatus_HostsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clusterstatus_HostsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clusterstatus_HostReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clusterstatus_HostReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024cluster_status.proto\022\rclusterstatus\"\016\n" +
      "\014HostsRequest\"\240\001\n\tHostReply\022\020\n\010hostname\030" +
      "\001 \001(\t\022\014\n\004port\030\002 \001(\005\0223\n\006status\030\003 \001(\0162#.cl" +
      "usterstatus.HostReply.HostStatus\">\n\nHost" +
      "Status\022\013\n\007STOPPED\020\000\022\013\n\007PENDING\020\001\022\t\n\005MIXE" +
      "D\020\002\022\013\n\007STARTED\020\0032W\n\rClusterStatus\022F\n\tLis" +
      "tHosts\022\033.clusterstatus.HostsRequest\032\030.cl" +
      "usterstatus.HostReply\"\0000\001B=\n%com.cleo.cl" +
      "arify.server.clusterstatusB\022ClusterStatu" +
      "sProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_clusterstatus_HostsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clusterstatus_HostsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clusterstatus_HostsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_clusterstatus_HostReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_clusterstatus_HostReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clusterstatus_HostReply_descriptor,
        new java.lang.String[] { "Hostname", "Port", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
