// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster_status.proto

package com.cleo.clarify.server.clusterstatus;

public interface HostsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clusterstatus.HostsRequest)
    com.google.protobuf.MessageOrBuilder {
}
