// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster_status.proto

package com.cleo.clarify.server.clusterstatus;

/**
 * Protobuf type {@code clusterstatus.HostReply}
 */
public  final class HostReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clusterstatus.HostReply)
    HostReplyOrBuilder {
  // Use HostReply.newBuilder() to construct.
  private HostReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HostReply() {
    hostname_ = "";
    port_ = 0;
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private HostReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostname_ = s;
            break;
          }
          case 16: {

            port_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cleo.clarify.server.clusterstatus.ClusterStatusProto.internal_static_clusterstatus_HostReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cleo.clarify.server.clusterstatus.ClusterStatusProto.internal_static_clusterstatus_HostReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cleo.clarify.server.clusterstatus.HostReply.class, com.cleo.clarify.server.clusterstatus.HostReply.Builder.class);
  }

  /**
   * Protobuf enum {@code clusterstatus.HostReply.HostStatus}
   */
  public enum HostStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STOPPED = 0;</code>
     */
    STOPPED(0),
    /**
     * <code>PENDING = 1;</code>
     */
    PENDING(1),
    /**
     * <code>MIXED = 2;</code>
     */
    MIXED(2),
    /**
     * <code>STARTED = 3;</code>
     */
    STARTED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STOPPED = 0;</code>
     */
    public static final int STOPPED_VALUE = 0;
    /**
     * <code>PENDING = 1;</code>
     */
    public static final int PENDING_VALUE = 1;
    /**
     * <code>MIXED = 2;</code>
     */
    public static final int MIXED_VALUE = 2;
    /**
     * <code>STARTED = 3;</code>
     */
    public static final int STARTED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HostStatus valueOf(int value) {
      return forNumber(value);
    }

    public static HostStatus forNumber(int value) {
      switch (value) {
        case 0: return STOPPED;
        case 1: return PENDING;
        case 2: return MIXED;
        case 3: return STARTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HostStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HostStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HostStatus>() {
            public HostStatus findValueByNumber(int number) {
              return HostStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cleo.clarify.server.clusterstatus.HostReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final HostStatus[] VALUES = values();

    public static HostStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HostStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:clusterstatus.HostReply.HostStatus)
  }

  public static final int HOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostname_;
  /**
   * <code>string hostname = 1;</code>
   */
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }
  /**
   * <code>string hostname = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private int port_;
  /**
   * <code>int32 port = 2;</code>
   */
  public int getPort() {
    return port_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
   */
  public com.cleo.clarify.server.clusterstatus.HostReply.HostStatus getStatus() {
    com.cleo.clarify.server.clusterstatus.HostReply.HostStatus result = com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.valueOf(status_);
    return result == null ? com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostname_);
    }
    if (port_ != 0) {
      output.writeInt32(2, port_);
    }
    if (status_ != com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.STOPPED.getNumber()) {
      output.writeEnum(3, status_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostname_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, port_);
    }
    if (status_ != com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.STOPPED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cleo.clarify.server.clusterstatus.HostReply)) {
      return super.equals(obj);
    }
    com.cleo.clarify.server.clusterstatus.HostReply other = (com.cleo.clarify.server.clusterstatus.HostReply) obj;

    boolean result = true;
    result = result && getHostname()
        .equals(other.getHostname());
    result = result && (getPort()
        == other.getPort());
    result = result && status_ == other.status_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostname().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cleo.clarify.server.clusterstatus.HostReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cleo.clarify.server.clusterstatus.HostReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clusterstatus.HostReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clusterstatus.HostReply)
      com.cleo.clarify.server.clusterstatus.HostReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cleo.clarify.server.clusterstatus.ClusterStatusProto.internal_static_clusterstatus_HostReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cleo.clarify.server.clusterstatus.ClusterStatusProto.internal_static_clusterstatus_HostReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cleo.clarify.server.clusterstatus.HostReply.class, com.cleo.clarify.server.clusterstatus.HostReply.Builder.class);
    }

    // Construct using com.cleo.clarify.server.clusterstatus.HostReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      hostname_ = "";

      port_ = 0;

      status_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cleo.clarify.server.clusterstatus.ClusterStatusProto.internal_static_clusterstatus_HostReply_descriptor;
    }

    public com.cleo.clarify.server.clusterstatus.HostReply getDefaultInstanceForType() {
      return com.cleo.clarify.server.clusterstatus.HostReply.getDefaultInstance();
    }

    public com.cleo.clarify.server.clusterstatus.HostReply build() {
      com.cleo.clarify.server.clusterstatus.HostReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cleo.clarify.server.clusterstatus.HostReply buildPartial() {
      com.cleo.clarify.server.clusterstatus.HostReply result = new com.cleo.clarify.server.clusterstatus.HostReply(this);
      result.hostname_ = hostname_;
      result.port_ = port_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cleo.clarify.server.clusterstatus.HostReply) {
        return mergeFrom((com.cleo.clarify.server.clusterstatus.HostReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cleo.clarify.server.clusterstatus.HostReply other) {
      if (other == com.cleo.clarify.server.clusterstatus.HostReply.getDefaultInstance()) return this;
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cleo.clarify.server.clusterstatus.HostReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cleo.clarify.server.clusterstatus.HostReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hostname_ = "";
    /**
     * <code>string hostname = 1;</code>
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostname = 1;</code>
     */
    public Builder setHostname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 1;</code>
     */
    public Builder clearHostname() {
      
      hostname_ = getDefaultInstance().getHostname();
      onChanged();
      return this;
    }
    /**
     * <code>string hostname = 1;</code>
     */
    public Builder setHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostname_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
     */
    public com.cleo.clarify.server.clusterstatus.HostReply.HostStatus getStatus() {
      com.cleo.clarify.server.clusterstatus.HostReply.HostStatus result = com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.valueOf(status_);
      return result == null ? com.cleo.clarify.server.clusterstatus.HostReply.HostStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
     */
    public Builder setStatus(com.cleo.clarify.server.clusterstatus.HostReply.HostStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:clusterstatus.HostReply)
  }

  // @@protoc_insertion_point(class_scope:clusterstatus.HostReply)
  private static final com.cleo.clarify.server.clusterstatus.HostReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cleo.clarify.server.clusterstatus.HostReply();
  }

  public static com.cleo.clarify.server.clusterstatus.HostReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HostReply>
      PARSER = new com.google.protobuf.AbstractParser<HostReply>() {
    public HostReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HostReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HostReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HostReply> getParserForType() {
    return PARSER;
  }

  public com.cleo.clarify.server.clusterstatus.HostReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

