// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster_status.proto

package com.cleo.clarify.server.clusterstatus;

public interface HostReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clusterstatus.HostReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostname = 1;</code>
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.clusterstatus.HostReply.HostStatus status = 3;</code>
   */
  com.cleo.clarify.server.clusterstatus.HostReply.HostStatus getStatus();
}
